#pragma config(Sensor, port3,  color,          sensorVexIQ_Color12Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		switch(SensorValue[color])
		{
			case 0:
			writeDebugStreamLine("color: no color");
			wait1Msec(3000);
			break;

			case 1:
			playTone(261.6, 300);
			while(bSoundActive) {};
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);

			case 2:
			playTone(293.7, 100);
			while(bSoundActive) {};
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);
			break;

			case 3:
			playTone(329.7, 100);
			while(bSoundActive) {};
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);

			case 4:
			playTone(349.2, 100);
			while(bSoundActive) {};
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);
			break;

			case 5:
			playTone(392, 100);
			while(bSoundActive) {};
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);
			break;

			case 6:
			playTone(440, 100);
			while(bSoundActive) {};
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);
			break;

			case 7:
			playTone(493.9, 100);
			while(bSoundActive) {};
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);
			break;

			default:
			break;

		}
		sleep(3000);
	}
}
