#pragma config(Sensor, port2,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor2,          motorB,        tmotorNone, openLoop)
#pragma config(Motor,  motor3,          motorC,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int FV = SensorValue[gyro];
	int Gyro_value;
	while(1)
	{
		Gyro_value = SensorValue[gyro]-FV;
		motor[motorB] = 70;
		motor[motorC] = 70+Gyro_value;
	}
}
