#pragma config(Sensor, port1,  touch,          sensorVexIQ_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(SensorValue[touch] == 0)
	{
		setLEDColor(2);
	}
	motor[motorB] = 20;
	motor[motorC] = 20;
	wait1Msec(1000);
}
