#pragma config(Sensor, port2,  gyro,           sensorVexIQ_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		writeDebugStreamLine("Gyro: %d", SensorValue[gyro]);
		wait1Msec(1000);
	}
}
