#pragma config(Sensor, port2,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor2,          lm,            tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int gyroRate = 0;
	while(1)
	{
		writeDebugStreamLine("Gyro: %d", SensorValue[gyro]);
		if(gyroRate > 100) gyroRate = 100;
		if(gyroRate < -100) gyroRate = -100;

		motor[lm] = gyroRate;
		wait1Msec(1000);
	}
}
