#pragma config(Sensor, port2,  gyro,           sensorVexIQ_Gyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int FV= SensorValue[gyro];
	int gyroValue;

	while(1)
	{
		gyroValue = SensorValue[gyro] - FV;
		writeDebugStreamLine("Gyro: %d", SensorValue[gyro]);
		if(gyroValue > 70)
		{
			gyroValue = 70;
		}
		if(gyroValue < -70)
		{
			gyroValue = -70;
		}

		motor[motorB] = 30 - gyroValue);
		motor[motorC] = 30;
	}
}
