#pragma config(Sensor, port3,  color,          sensorVexIQ_Color12Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	string colstr = colorNone;
	while(1)
	{
		color = getColorName(color);
		writeDebugStreamLine("Color Detected: %s", colstr);
		switch(SensorValue[color]
		{
			case 5:
			setLEDColor(ledRed);
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);
			break;

			case 4:
			setLEDColor(ledOrange);
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);
			break;

			case 3:
			setLEDColor(ledGreen);
			writeDebugStreamLine("color: %d", SensorValue[color]);
			wait1Msec(3000);
			break;

			default:
			setLEDColor(ledOff);
			break;
		}
	}
}
