#pragma config(Sensor, port2,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor2,          motorB,        tmotorNone, openLoop)
#pragma config(Motor,  motor3,          motorC,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void computeDegree(int height, int degree)
{
	int FV = SensorValue[gyro];
	while(SensorValue[gyro] <= degree+FV)
	{
		motor[motorB] = 30;
		motor[motorC] = -30;
	}

	motor[motorB] = 0;
	motor[motorC] = 0;

	float distance = height/cosDegrees(degree);
	writeDebugStreamLine("distance = %fcm", distance);
	sleep(1000);

	int deg = (360*distance)/17.58;

	moveMotorTarget(motorB, deg, 30);
	moveMotorTarget(motorC, deg, 30);
	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);
}
