#pragma config(Sensor, port2,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor2,          motorB,        tmotorNone, openLoop)
#pragma config(Motor,  motor3,          motorC,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "compute.c"
#define height 30
#define degree 60

task main()
{
	computeDegree(height, degree);
}
