#pragma config(Motor,  motor2,          motorB,        tmotorNone, openLoop)
#pragma config(Motor,  motor3,          motorC,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define speed 50
#define time 2000

task main()
{
	motor[motorB] = speed;
	motor[motorC] = speed;
}
