
#pragma config(Motor,  motor2,          motorB,        tmotorNone, openLoop)
#pragma config(Motor,  motor3,          motorC,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "move.c"

task main()
{
	foward(30, 2000);
	reverse(-30, 2000);
	foward(30, 2000);
	reverse(-30, 2000);
}
