#pragma config(Motor,  motor2,          motorB,        tmotorNone, openLoop)
#pragma config(Motor,  motor3,          motorC,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void foward(int speed, int time)
{
	motor[motorB] = speed;
	motor[motorC] = speed;
	wait1Msec(time);
}

void reverse(int speed, int time)
{
	motor[motorB] = speed;
	motor[motorC] = speed;
	wait1Msec(time);
}
