#pragma config(Sensor, port1,  Touch,          sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		while(SensorValue[Touch] == 1) {}
		setLEDColor(7);
		sleep(1000);
		motor[motorB] = 50;
		motor[motorC] = 50;
		wait1Msec(1000);

		while(SensorValue[Touch] == 0) {}
		setLEDColor(8);
		sleep(1000);
		motor[motorB] = -50;
		motor[motorC] = -50;
		wait1Msec(1000);

		while(getButtonPress(buttonUp)) {}
		setLEDColor(9);
		sleep(1000);
		motor[motorB] = 50;
		motor[motorC] = 50;
		wait1Msec(1000);

		while(getButtonPress(buttonDown)) {}
		setLEDColor(8);
		sleep(1000);
		motor[motorB] = -50;
		motor[motorC] = -50;
		wait1Msec(1000);
		playTone(784, 100);
		while(bSoundActive) {};
		wait1Msec(1000);
	}

}
