#pragma config(Sensor, port2,  gyro,           sensorVexIQ_Gyro)
#pragma config(Motor,  motor2,          motorB,        tmotorNone, openLoop)
#pragma config(Motor,  motor3,          motorC,        tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int FV = SensorValue[gyro];
	while(SensorValue[gyro] <= 60+FV)
	{
		motor[motorB] = 30;
		motor[motorC] = -30;
	}

	motor[motorB] = 0;
	motor[motorC] = 0;

	float distance = 30/cosDegrees(60);
	writeDebugStreamLine("distance = %fcm", distance);
	sleep(1000);

	int degree = (360*distance)/17.58;

	moveMotorTarget(motorB, degree, 30);
	moveMotorTarget(motorC, degree, 30);
	waitUntilMotorStop(motorB);
	waitUntilMotorStop(motorC);
}
