#pragma config(Sensor, port3,  color,          sensorVexIQ_ColorHue)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int light_value;

	while(true)
	{
		light_value = SensorValue(color);
		motor[motorB] = light_value;
		motor[motorC] = light_value;
	}
}
