#pragma config(Sensor, port3,  color,          sensorVexIQ_ColorHue)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD 30
task main()
{
	int count = 0;

	while(true)
	{
		motor[motorB] = 20;
		motor[motorC] = 20;

		if(SensorValue[color] <= THRESHOLD)
		{
			count++;
			if(count >= 3) break;
			wait10Msec(500);
		}
	}

	motor[motorB] = 20;
	motor[motorC] = 20;
}
