#pragma config(Sensor, port3,  color,          sensorVexIQ_ColorHue)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define THRESHOLD 30
task main()
{
	motor[motorB] = 20;
	motor[motorC] = 20;

	while(SensorValue[color] > THRESHOLD) {}
	while(SensorValue[color] <= THRESHOLD) {}
	while(SensorValue[color] > THRESHOLD) {}
}
