#pragma config(Sensor, port4,  sonar,          sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
	{
		writeDebugStreamLine("distance: %d", SensorValue[sonar]);
		wait1Msec(50);
	}
}
