#pragma config(Sensor, port4,  sonar,          sensorVexIQ_Distance)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorB] = 50;
	motor[motorB] = 50;
	while(SensorValue[sonar] > 10) {}
	motor[motorB] = 0;
	motor[motorB] = 0;
}
